import type {
  AgentInvocation,
  AgentRegistration,
  AgentReport,
  ApprovalRequest,
  CapabilitiesProjection,
  Artifact,
  ArtifactReference,
  AuthorityEnvelope,
  BudgetEnvelope,
  BudgetReservation,
  CostObservation,
  DecisionRecord,
  EnvironmentRevision,
  Escalation,
  ExecutionPlan,
  FailureRecord,
  JupyterSession,
  JupyterSessionRequest,
  MetricObservation,
  Notebook,
  NotebookCellRecord,
  ProviderConfiguration,
  ProviderCredential,
  ProviderModel,
  ResourceEnvelope,
  RetryPolicy,
  Run,
  RunAttempt,
  RuntimeCommand,
  RuntimeEvent,
  RuntimeProfile,
  StateAssertion,
  ToolGrant,
  UsageObservation,
  Workflow,
} from '../src/contracts.js';
import type { Id, HashSha256 } from '../src/ids.js';
import type { JsonValue } from '../src/json.js';
import type { Actor, Money, Quantity, ResourceSelector, TenantRef } from '../src/primitives.js';

export const id = '018f0c4b-4e00-7abc-8def-0123456789ab' as Id;
export const otherId = '018f0c4b-4e01-7abc-8def-0123456789ab' as Id;
export const hash =
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' as HashSha256;
export const time = '2026-08-02T00:00:00.000Z';

export const tenant: TenantRef = { tenantId: id, workspaceId: otherId };
export const actor: Actor = { actorId: id, type: 'human', displayName: 'Fixture user' };
export const agentActor: Actor = { actorId: otherId, type: 'agent', displayName: 'Fixture agent' };
export const money: Money = { amountMinor: 1250, currency: 'USD' };
export const quantity: Quantity = { value: 10, unit: 'tokens' };
export const resource: ResourceSelector = { kind: 'dataset', id: 'dataset-fixture', version: 1 };

export const providerConfiguration: ProviderConfiguration = {
  schemaVersion: 1,
  providerConfigurationId: id,
  tenant,
  providerId: 'deterministic',
  providerType: 'deterministic',
  displayName: 'Deterministic fixture provider',
  endpoint: 'local://deterministic',
  defaultModelId: 'fixture-model',
  capabilities: ['streaming', 'structured-output'],
  supportedModalities: ['text'],
  modelDiscoveryMode: 'configured',
  state: 'callable',
  authenticationState: 'not_applicable',
  local: true,
  timeoutMs: 120_000,
  retryMaxAttempts: 2,
  usagePolicy: { maxTokensPerRequest: 4096 },
  createdAt: time,
  updatedAt: time,
};

export const providerCredential: ProviderCredential = {
  schemaVersion: 1,
  credentialId: otherId,
  tenant,
  providerConfigurationId: id,
  authMethod: 'none',
  status: 'active',
  createdAt: time,
  updatedAt: time,
};

export const providerModel: ProviderModel = {
  schemaVersion: 1,
  providerModelId: otherId,
  tenant,
  providerConfigurationId: id,
  providerId: 'deterministic',
  modelId: 'fixture-model',
  displayName: 'Deterministic fixture model',
  inputModalities: ['text'],
  outputModalities: ['text'],
  capabilities: ['streaming', 'structured-output'],
  dataClasses: ['public', 'internal'],
  billingMode: 'local',
  local: true,
  state: 'ready',
  createdAt: time,
  updatedAt: time,
};

export const runtimeProfile: RuntimeProfile = {
  schemaVersion: 1,
  runtimeProfileId: id,
  tenant,
  runtimeType: 'local-host',
  displayName: 'Fixture local runtime',
  state: 'ready',
  cpuMillicores: 1000,
  memoryBytes: 1024 * 1024 * 1024,
  networkPolicy: 'loopback-only',
  createdAt: time,
  updatedAt: time,
};

export const environmentRevision: EnvironmentRevision = {
  schemaVersion: 1,
  environmentId: id,
  tenant,
  name: 'fixture-environment',
  revision: 1,
  runtimeProfileId: id,
  lockfileHash: hash,
  state: 'ready',
  createdAt: time,
};

export const authority: AuthorityEnvelope = {
  schemaVersion: 1,
  envelopeId: id,
  tenant,
  issuer: actor,
  subjectAgentId: otherId,
  workflowId: id,
  invocationId: id,
  tier: 1,
  harnessVersion: '1.0.0',
  permittedActions: ['dataset.read'],
  capabilities: ['dataset.read'],
  resourceScopes: [resource],
  allowedArtifactReads: [resource],
  allowedArtifactWrites: [],
  allowedChildAgentTypes: ['data-engineer'],
  maxChildCount: 2,
  toolOperations: ['catalog.readSchema'],
  issuedAt: time,
  expiresAt: '2026-08-02T01:00:00.000Z',
  nonce: 'fixture-nonce-123456',
  policyVersion: 'policy.v1',
  revocationEpoch: 0,
  integrityProof: hash,
};

export const resourceEnvelope: ResourceEnvelope = {
  limits: {
    cpuMillicores: 1000,
    memoryBytes: 1024 * 1024,
    wallTimeMs: 60_000,
    outputBytes: 1024 * 1024,
    storageBytes: 1024 * 1024,
    processCount: 1,
  },
  networkAllowlist: [],
  readOnlyArtifactMounts: true,
};

export const retry: RetryPolicy = {
  maxAttempts: 3,
  backoffMs: 100,
  maxBackoffMs: 1000,
  retryableErrorCodes: ['EXTERNAL_DEPENDENCY_UNAVAILABLE'],
};

export const budget: BudgetEnvelope = {
  budgetId: id,
  limit: 10000,
  reserved: 1250,
  consumed: 100,
  currency: 'USD',
};

export const artifactReference: ArtifactReference = {
  schemaVersion: 1,
  tenant,
  artifactId: id,
  version: 1,
  contentHash: hash,
  mediaType: 'application/json',
  sizeBytes: 42,
  createdAt: time,
  uri: 'cas://aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
};

export const decision: DecisionRecord = {
  decisionId: id,
  kind: 'dataset.accepted',
  summary: 'Fixture decision',
  decidedBy: agentActor,
  decidedAt: time,
  evidence: [artifactReference],
};

export const metric: MetricObservation = {
  metricId: id,
  name: 'rows',
  value: 10,
  unit: 'items',
  observedAt: time,
  labels: { source: 'fixture' },
};

export const cost: CostObservation = {
  observationId: id,
  amount: money,
  source: 'fixture',
  observedAt: time,
  externalRequestId: 'request-fixture',
};

export const failure: FailureRecord = {
  failureId: id,
  code: 'VALIDATION_INVALID_INPUT',
  message: 'Fixture failure',
  retryable: false,
  occurredAt: time,
  evidence: [artifactReference],
};

export const samples: Record<string, JsonValue> = {
  Id: id,
  HashSha256: hash,
  SchemaVersion: 1,
  UtcInstant: time,
  TenantRef: tenant,
  Actor: actor,
  Money: money,
  Quantity: quantity,
  ResourceSelector: resource,
  CapabilitiesProjection: {
    schemaVersion: 1,
    runtimeMode: 'managed-local-daemon',
    workspaceMode: 'personal_local',
    policyEnforcement: 'local',
    projectionVersion: 1,
    generatedAt: time,
    projections: ['projects', 'runs'],
    commands: ['CreateProject'],
    capabilities: {
      'model-runtime': {
        enabled: true,
        status: 'ready',
        executor: 'deterministic-fixture',
        commands: ['run prompt'],
      },
      'queries.execute': {
        enabled: false,
        status: 'unavailable',
        reason: 'Query runtime is not configured.',
      },
    },
  } satisfies CapabilitiesProjection,
  ProviderConfiguration: providerConfiguration,
  ProviderCredential: providerCredential,
  ProviderModel: providerModel,
  RuntimeProfile: runtimeProfile,
  EnvironmentRevision: environmentRevision,
  NotebookCellRecord: {
    schemaVersion: 1,
    cellId: id,
    cellType: 'python',
    sourceHash: hash,
    state: 'completed',
    executionCount: 1,
    inputReferences: [],
    outputReferences: [artifactReference],
    createdAt: time,
    updatedAt: time,
  } satisfies NotebookCellRecord,
  Notebook: {
    schemaVersion: 1,
    notebookId: id,
    tenant,
    title: 'Fixture notebook',
    revision: 1,
    runtimeProfileId: id,
    environmentRevisionId: id,
    state: 'active',
    cellIds: [id],
    createdAt: time,
    updatedAt: time,
  } satisfies Notebook,
  JupyterSessionRequest: {
    schemaVersion: 1,
    sessionRequestId: id,
    tenant,
    notebookId: id,
    runtimeProfileId: id,
    environmentRevisionId: id,
    requestedAt: time,
  } satisfies JupyterSessionRequest,
  JupyterSession: {
    schemaVersion: 1,
    sessionId: id,
    tenant,
    notebookId: id,
    user: actor,
    runtimeProfileId: id,
    environmentRevisionId: id,
    runtime: 'jupyter',
    endpoint: 'http://127.0.0.1:8888/lab',
    kernelId: 'fixture-kernel',
    state: 'ready',
    idleTimeoutMs: 900_000,
    lastActivityAt: time,
    associatedRunIds: [otherId],
    createdAt: time,
    updatedAt: time,
  } satisfies JupyterSession,
  Run: {
    schemaVersion: 1,
    runId: id,
    tenant,
    requestedAction: 'model.invoke',
    initiatingPrincipal: actor,
    sourceInterface: 'tui',
    providerConfigurationId: id,
    providerId: 'deterministic',
    modelId: 'fixture-model',
    runtimeProfileId: id,
    environmentRevisionId: id,
    inputReferences: [],
    state: 'succeeded',
    attemptIds: [otherId],
    createdAt: time,
    updatedAt: time,
    startedAt: time,
    completedAt: time,
  } satisfies Run,
  RunAttempt: {
    schemaVersion: 1,
    attemptId: otherId,
    runId: id,
    tenant,
    attemptNumber: 1,
    state: 'succeeded',
    providerId: 'deterministic',
    modelId: 'fixture-model',
    runtimeProfileId: id,
    startedAt: time,
    completedAt: time,
    durationMs: 5,
    outputReferences: [artifactReference],
  } satisfies RunAttempt,
  RuntimeCommand: {
    schemaVersion: 1,
    commandId: id,
    commandType: 'ValidateDataset',
    tenant,
    actor,
    issuedAt: time,
    idempotencyKey: 'fixture-idempotency-key',
    correlationId: id,
    payload: { dataset: 'fixture' },
  } satisfies RuntimeCommand,
  Workflow: {
    schemaVersion: 1,
    workflowId: id,
    tenant,
    objective: 'Validate the fixture dataset',
    state: 'planning',
    planVersion: 0,
    createdAt: time,
    updatedAt: time,
    invocationIds: [],
    completionCriteria: ['A report is accepted'],
  } satisfies Workflow,
  ExecutionPlan: {
    schemaVersion: 1,
    planId: id,
    workflowId: id,
    version: 1,
    steps: [
      {
        stepId: id,
        tier: 1,
        agentType: 'data-engineer',
        dependsOn: [],
        inputArtifactIds: [],
        requiredCapabilities: ['dataset.read'],
        approvalRequired: false,
        acceptanceCriteria: ['Schema is present'],
      },
    ],
    createdAt: time,
    digest: hash,
  } satisfies ExecutionPlan,
  AgentInvocation: {
    schemaVersion: 1,
    invocationId: id,
    workflowId: id,
    tenant,
    tier: 1,
    agentType: 'data-engineer',
    harnessVersion: '1.0.0',
    input: { dataset: 'fixture' },
    authority,
    resource: resourceEnvelope,
    retry,
    budget,
    state: 'created',
    attempt: 0,
    createdAt: time,
    correlationId: id,
  } satisfies AgentInvocation,
  AgentReport: {
    schemaVersion: 1,
    reportId: id,
    invocationId: id,
    agentType: 'data-engineer',
    tier: 1,
    harnessVersion: '1.0.0',
    status: 'success',
    output: { accepted: true },
    decisions: [decision],
    artifacts: [artifactReference],
    metrics: [metric],
    costs: [cost],
    failures: [],
    childInvocationIds: [],
    stateAssertions: [],
    producedAt: time,
  } satisfies AgentReport,
  Artifact: {
    schemaVersion: 1,
    reference: artifactReference,
    state: 'valid',
    createdBy: actor,
    lineage: [],
    content: { rows: 10 },
  } satisfies Artifact,
  ArtifactReference: artifactReference,
  RuntimeEvent: {
    schemaVersion: 1,
    eventId: id,
    eventName: 'workflow.created.v1',
    tenant,
    aggregateType: 'workflow',
    aggregateId: id,
    aggregateVersion: 1,
    occurredAt: time,
    actor,
    correlationId: id,
    payload: { objective: 'fixture' },
  } satisfies RuntimeEvent,
  ApprovalRequest: {
    schemaVersion: 1,
    approvalId: id,
    tenant,
    actionDigest: hash,
    actionType: 'compute.allocate',
    requestedBy: agentActor,
    resources: [resource],
    estimatedCost: money,
    policyVersion: 'policy.v1',
    revocationEpoch: 0,
    state: 'pending',
    requestedAt: time,
    expiresAt: '2026-08-02T01:00:00.000Z',
  } satisfies ApprovalRequest,
  BudgetEnvelope: budget,
  BudgetReservation: {
    reservationId: id,
    budgetId: id,
    amount: money,
    category: 'compute',
    state: 'requested',
    createdAt: time,
  } satisfies BudgetReservation,
  UsageObservation: {
    usageId: id,
    invocationId: id,
    quantity,
    observedAt: time,
    cost: money,
  } satisfies UsageObservation,
  AuthorityEnvelope: authority,
  ResourceEnvelope: resourceEnvelope,
  RetryPolicy: retry,
  FailureRecord: failure,
  AgentRegistration: {
    schemaVersion: 1,
    agentId: id,
    agentType: 'data-engineer',
    version: '1.0.0',
    tier: 1,
    supportedContracts: ['ExecutionPlan.v1', 'AgentReport.v1'],
    capabilities: ['dataset.read'],
    status: 'active',
  } satisfies AgentRegistration,
  ToolGrant: {
    schemaVersion: 1,
    grantId: id,
    tenant,
    invocationId: id,
    toolName: 'catalog',
    operation: 'readSchema',
    issuedAt: time,
    expiresAt: '2026-08-02T01:00:00.000Z',
    authorityEnvelopeId: id,
    resourceScopes: [resource],
    maxUses: 2,
  } satisfies ToolGrant,
  DecisionRecord: decision,
  Escalation: {
    escalationId: id,
    reason: 'Fixture needs approval',
    requestedAt: time,
    requestedBy: agentActor,
    requiredTier: 0,
  } satisfies Escalation,
  StateAssertion: {
    assertionId: id,
    subjectType: 'artifact',
    subjectId: id,
    state: 'valid',
    assertedAt: time,
    evidence: [artifactReference],
  } satisfies StateAssertion,
  MetricObservation: metric,
  CostObservation: cost,
};
