import type { ResourcePageAction, ResourcePageConfig } from './ResourcePage';

const action = (
  command: string,
  label: string,
  visibleWhen?: readonly string[],
): ResourcePageAction => ({
  command,
  label,
  ...(visibleWhen === undefined ? {} : { visibleWhen }),
});

export const RESOURCE_PAGE_CONFIGS: Record<string, ResourcePageConfig> = {
  data: {
    page: 'data',
    title: 'Data',
    eyebrow: 'Dataset workspace',
    projection: 'catalog-datasets',
    collectionKeys: ['datasets'],
    resourceKey: 'dataset',
    icon: 'database',
    createCommand: 'CreateDataset',
    updateCommand: 'UpdateDataset',
    archiveCommand: 'ArchiveDataset',
    actions: [
      {
        ...action('ValidateDataset', 'Validate', ['active', 'failed']),
        payloadFrom: {
          sourceArtifactId: 'sourceArtifactId',
          sourceArtifactVersion: 'sourceArtifactVersion',
        },
      },
    ],
    upload: {
      accept: '.csv,.json,.jsonl,text/csv,application/json',
      mediaType: 'auto',
      label: 'Import and stage CSV or JSON data',
    },
    createLabel: 'Import dataset',
    description: 'Import, validate, and manage datasets used by platform workflows.',
    emptyDescription: 'Import a dataset to make it available to validation and workflow runs.',
  },
  catalog: {
    page: 'catalog',
    title: 'Catalog',
    eyebrow: 'Data and artifact catalog',
    projection: 'catalog-datasets',
    collectionKeys: ['datasets', 'artifacts'],
    resourceKey: 'dataset',
    icon: 'catalog',
    createCommand: 'CreateDataset',
    updateCommand: 'UpdateDataset',
    actions: [
      {
        ...action('ValidateDataset', 'Validate', ['active', 'failed']),
        payloadFrom: {
          sourceArtifactId: 'sourceArtifactId',
          sourceArtifactVersion: 'sourceArtifactVersion',
        },
      },
    ],
    description: 'Inspect datasets, artifacts, lineage, versions, and validation state.',
    emptyDescription: 'Catalog entries will appear after datasets or artifacts are registered.',
  },
  sql: {
    page: 'sql',
    title: 'SQL',
    eyebrow: 'Query workspace',
    projection: 'queries',
    collectionKeys: ['queries'],
    resourceKey: 'query',
    icon: 'terminal',
    createCommand: 'CreateQuery',
    updateCommand: 'UpdateQuery',
    actions: [
      action('RunQuery', 'Execute', ['active', 'failed', 'completed', 'cancelled']),
      action('CancelQuery', 'Cancel', ['running', 'queued', 'planning']),
    ],
    editorLabel: 'SQL statement',
    editorPlaceholder: 'SELECT …',
    editorRows: 10,
    editorField: 'query',
    createLabel: 'New query',
    description: 'Create, plan, execute, and inspect queries against connected data sources.',
    emptyDescription: 'Create a query to begin a governed data workflow.',
  },
  visualizations: {
    page: 'visualizations',
    title: 'Visualizations',
    eyebrow: 'Analysis outputs',
    projection: 'visualizations',
    collectionKeys: ['visualizations', 'charts'],
    resourceKey: 'visualization',
    icon: 'chart',
    createCommand: 'CreateVisualization',
    updateCommand: 'UpdateVisualization',
    archiveCommand: 'ArchiveVisualization',
    actions: [action('RefreshVisualization', 'Refresh', ['active', 'failed', 'completed'])],
    createLabel: 'New visualization',
    description: 'Turn governed query and model outputs into refreshable charts.',
    emptyDescription: 'Visualizations will appear after a query or run publishes an output.',
  },
  automations: {
    page: 'automations',
    title: 'Automations',
    eyebrow: 'Scheduled workflows',
    projection: 'automations',
    collectionKeys: ['automations'],
    resourceKey: 'automation',
    icon: 'automation',
    createCommand: 'CreateAutomation',
    updateCommand: 'UpdateAutomation',
    actions: [
      action('PauseAutomation', 'Pause', ['active', 'running']),
      action('ResumeAutomation', 'Resume', ['paused']),
    ],
    createLabel: 'New automation',
    description: 'Schedule governed workflows and monitor their trigger history.',
    emptyDescription: 'Create an automation when a workflow should run on a schedule or trigger.',
  },
  notebooks: {
    page: 'notebooks',
    title: 'Notebooks',
    eyebrow: 'Interactive analysis',
    projection: 'notebooks',
    collectionKeys: ['notebooks'],
    resourceKey: 'notebook',
    icon: 'notebook',
    createCommand: 'CreateNotebook',
    updateCommand: 'UpdateNotebook',
    archiveCommand: 'ArchiveNotebook',
    actions: [action('RunNotebook', 'Run', ['active', 'failed', 'completed'])],
    editorLabel: 'Notebook content',
    editorPlaceholder: 'Add narrative, code, or analysis instructions…',
    editorRows: 10,
    editorField: 'content',
    createLabel: 'New notebook',
    description: 'Compose analysis with governed data, models, and publishable artifacts.',
    emptyDescription: 'Create a notebook to combine narrative, code, data, and model outputs.',
  },
  code: {
    page: 'code',
    title: 'Code',
    eyebrow: 'Code workspace',
    projection: 'worktrees',
    collectionKeys: ['worktrees', 'repositories'],
    resourceKey: 'worktree',
    icon: 'code',
    createCommand: 'CreateWorktree',
    updateCommand: 'UpdateWorktree',
    archiveCommand: 'DeleteWorktree',
    archiveLabel: 'Delete',
    createLabel: 'New worktree',
    description: 'Work with connected repositories through brokered, scoped workspace access.',
    emptyDescription: 'Create a worktree after connecting a repository.',
  },
  worktrees: {
    page: 'worktrees',
    title: 'Worktrees',
    eyebrow: 'Isolated code workspaces',
    projection: 'worktrees',
    collectionKeys: ['worktrees'],
    resourceKey: 'worktree',
    icon: 'git-branch',
    createCommand: 'CreateWorktree',
    updateCommand: 'UpdateWorktree',
    archiveCommand: 'DeleteWorktree',
    archiveLabel: 'Delete',
    createLabel: 'New worktree',
    description: 'Create isolated workspaces for safe agent and developer changes.',
    emptyDescription: 'Worktrees will appear after a repository is connected.',
  },
  repositories: {
    page: 'repositories',
    title: 'Repositories',
    eyebrow: 'Source control',
    projection: 'repositories',
    collectionKeys: ['repositories'],
    resourceKey: 'repository',
    icon: 'repository',
    createCommand: 'CreateRepository',
    updateCommand: 'UpdateRepository',
    archiveCommand: 'ArchiveRepository',
    actions: [action('SyncRepository', 'Sync', ['active', 'failed', 'completed'])],
    createLabel: 'Add repository',
    description: 'Register and synchronize source repositories without exposing connector tokens.',
    emptyDescription: 'Connect GitHub or another brokered source before adding repositories.',
  },
  deployments: {
    page: 'deployments',
    title: 'Deployments',
    eyebrow: 'Model delivery',
    projection: 'deployment-traffic',
    collectionKeys: ['deployments'],
    resourceKey: 'deployment',
    icon: 'deploy',
    createCommand: 'CreateDeployment',
    updateCommand: 'UpdateDeployment',
    actions: [
      action('PromoteDeployment', 'Promote', ['active', 'ready', 'completed']),
      action('RollbackDeployment', 'Rollback', ['active', 'failed', 'completed']),
    ],
    createLabel: 'New deployment',
    description: 'Promote models and observe deployment health, traffic, and rollback state.',
    emptyDescription: 'Deployments will appear after a model or workflow output is promoted.',
  },
  environments: {
    page: 'environments',
    title: 'Environments',
    eyebrow: 'Execution targets',
    projection: 'environments',
    collectionKeys: ['environments'],
    resourceKey: 'environment',
    icon: 'monitor',
    createCommand: 'CreateEnvironment',
    updateCommand: 'UpdateEnvironment',
    archiveCommand: 'DeleteEnvironment',
    archiveLabel: 'Delete',
    createLabel: 'New environment',
    description: 'Manage local and hosted execution targets with explicit health and readiness.',
    emptyDescription: 'Add an environment to make a target available for deployment or runs.',
  },
  experiments: {
    page: 'experiments',
    title: 'Experiments',
    eyebrow: 'Model evaluation',
    projection: 'experiments',
    collectionKeys: ['experiments'],
    resourceKey: 'experiment',
    icon: 'flask',
    createCommand: 'CreateExperiment',
    updateCommand: 'UpdateExperiment',
    archiveCommand: 'ArchiveExperiment',
    createLabel: 'New experiment',
    description: 'Compare runs, models, prompts, and metrics in an auditable evaluation loop.',
    emptyDescription: 'Create an experiment to compare model or workflow behavior.',
  },
  pipelines: {
    page: 'pipelines',
    title: 'Pipelines',
    eyebrow: 'Reusable workflows',
    projection: 'pipelines',
    collectionKeys: ['pipelines'],
    resourceKey: 'pipeline',
    icon: 'pipeline',
    createCommand: 'CreatePipeline',
    updateCommand: 'UpdatePipeline',
    actions: [
      action('RunPipeline', 'Run', ['active', 'failed', 'completed', 'cancelled']),
      action('CancelPipeline', 'Cancel', ['running', 'queued', 'planning']),
    ],
    createLabel: 'New pipeline',
    description: 'Compose validated stages and execute repeatable data and ML workflows.',
    emptyDescription: 'Create a pipeline to make a workflow reusable and observable.',
  },
  resources: {
    page: 'resources',
    title: 'Resources',
    eyebrow: 'Compute and storage',
    projection: 'resources',
    collectionKeys: ['resources'],
    resourceKey: 'resource',
    icon: 'grid',
    createCommand: 'CreateResource',
    updateCommand: 'UpdateResource',
    archiveCommand: 'ReleaseResource',
    archiveLabel: 'Release',
    createLabel: 'Allocate resource',
    description: 'Inspect governed compute, storage, and execution allocations.',
    emptyDescription: 'Resources will appear when a workflow or environment requests capacity.',
  },
  incidents: {
    page: 'incidents',
    title: 'Incidents',
    eyebrow: 'Operational response',
    projection: 'incidents',
    collectionKeys: ['incidents'],
    resourceKey: 'incident',
    icon: 'warning',
    createCommand: 'CreateIncident',
    updateCommand: 'UpdateIncident',
    actions: [
      action('AcknowledgeIncident', 'Acknowledge', ['active', 'open']),
      action('ResolveIncident', 'Resolve', ['active', 'acknowledged', 'open']),
    ],
    createLabel: 'Open incident',
    description: 'Track platform failures and coordinate recovery across affected resources.',
    emptyDescription: 'No incidents are currently recorded for this workspace.',
  },
  governance: {
    page: 'governance',
    title: 'Governance',
    eyebrow: 'Policy controls',
    projection: 'governance',
    collectionKeys: ['policies', 'governance'],
    resourceKey: 'policy',
    icon: 'shield',
    createCommand: 'CreateGovernancePolicy',
    updateCommand: 'UpdateGovernancePolicy',
    archiveCommand: 'ArchiveGovernancePolicy',
    createLabel: 'New policy',
    description: 'Review and manage policies governing data, tools, models, and deployments.',
    emptyDescription: 'Governance policies will appear after policy administration is enabled.',
  },
  audit: {
    page: 'audit',
    title: 'Audit',
    eyebrow: 'Immutable activity',
    projection: 'audit-timeline',
    collectionKeys: ['entries', 'events', 'records'],
    resourceKey: 'event',
    icon: 'document',
    description: 'Inspect immutable policy, connector, model, workflow, and command activity.',
    emptyDescription: 'Audit entries will appear as the workspace processes governed activity.',
  },
};
